# نام ورک‌فلو
name: Build Cordova Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    # استفاده از آخرین نسخه اوبونتو
    runs-on: ubuntu-latest

    steps:
      # مرحله ۱: دریافت کد از ریپازیتوری
      - name: Checkout Repository
        uses: actions/checkout@v4

      # مرحله ۲: آماده‌سازی محیط - نصب Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # مرحله ۳: آماده‌سازی محیط - نصب Java JDK 17
      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # مرحله ۴: آماده‌سازی محیط - نصب Android SDK (بسیار مهم)
      # این مرحله باید قبل از اجرای هر دستور کوردوا اجرا شود
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          build-tools: "34.0.0"
          platform: "android-34"
          cmdline-tools: "latest"

      # مرحله ۵: نصب ابزارهای پروژه
      - name: Install Cordova and Dependencies
        run: |
          npm install -g cordova
          npm install

      # مرحله ۶: افزودن پلتفرم اندروید
      - name: Add Android Platform
        run: cordova platform add android@latest

      # مرحله ۷ (اختیاری ولی مفید): نمایش فایل‌های ساخته شده برای دیباگ
      - name: List files in platforms directory
        run: ls -R platforms

      # مرحله ۸: اعطای دسترسی اجرایی به Gradle
      - name: Grant Execute Permission to gradlew
        run: chmod +x platforms/android/gradlew

      # مرحله ۹: ساخت اپلیکیشن اندروید
      - name: Build Android App (Debug)
        run: cordova build android

      # مرحله ۱۰: آپلود فایل APK خروجی
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
