name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # استفاده از Java 17 برای جلوگیری از خطای Gradle
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Cordova CLI
      run: npm install -g cordova

    - name: Install dependencies
      run: npm install

    - name: Add Android platform
      run: cordova platform add android@latest

    - name: Build Android Debug APK
      run: cordova build android

    # استفاده از نسخه v4 برای جلوگیری از خطای deprecated
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hrlink-apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
